//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articoli
    {
        public int IdArticolo { get; set; }
        public string CodArt { get; set; }
        public string DesArt { get; set; }
        public string CodFamiglia { get; set; }
    
        public virtual Famiglie Famiglie { get; set; }
    }
}
