// <auto-generated />
namespace ConsoleApp1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0-rc1-19458-04")]
    public sealed partial class CostoStandardSuArticoli : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CostoStandardSuArticoli));
        
        string IMigrationMetadata.Id
        {
            get { return "201909201706518_CostoStandardSuArticoli"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
